# Name of the workflow
# This workflow automates the Terraform infrastructure deployment and Docker image build process.
name: Terraform CI/CD Pipeline

# Event triggers
# The workflow is triggered on:
# 1. Push events to the 'main' branch.
# 2. Pull requests targeting the 'main' branch.
on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

# Define the job(s) for the workflow
jobs:
  build:
    # Specify the environment where the job runs
    # 'ubuntu-latest' is a GitHub-hosted runner with an Ubuntu Linux image.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      # This step checks out the code from the repository so it can be accessed during the workflow.
      - name: Checkout Code
        uses: actions/checkout@v3  # GitHub Action to check out repository code

      # Step 2: Set up Terraform
      # Installs Terraform CLI for use in subsequent steps.
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2  # GitHub Action to set up Terraform
        with:
          terraform_version: 1.10.0  # Specify the Terraform version to use

      # Step 3: Initialize Terraform
      # Initializes the Terraform working directory and downloads necessary provider plugins.
      - name: Terraform Init
        working-directory: ./terraform  # Specify the Terraform configuration directory
        run: terraform init  # Initialize Terraform

      # Step 4: Validate Terraform configuration
      # Validates the Terraform configuration to ensure it's syntactically correct.
      - name: Terraform Validate
        working-directory: ./terraform  # Specify the Terraform configuration directory
        run: terraform validate  # Validate Terraform code

      # Step 5: Generate Terraform execution plan
      # Creates a plan for infrastructure changes, saving it to a file named 'tfplan'.
      - name: Terraform Plan
        working-directory: ./terraform  # Specify the Terraform configuration directory
        run: terraform plan -out=tfplan  # Generate an execution plan and save it as 'tfplan'

      # Step 6: Manual Approval (Optional)
      # Inserts a manual approval step before applying changes to the infrastructure.
      - name: Manual Approval
        uses: hmarr/auto-approve-action@v2  # GitHub Action for manual approval
        with:
          approval_mode: true  # Require manual approval

      # Step 7: Apply Terraform execution plan
      # Applies the changes defined in the 'tfplan' file if the event is a push to the main branch.
      - name: Terraform Apply
        if: github.event_name == 'push'  # Only execute on a push event
        working-directory: ./terraform  # Specify the Terraform configuration directory
        run: terraform apply tfplan  # Apply the execution plan

      # Step 8: Build Docker image
      # Builds the Docker image for the Node.js application using the Dockerfile in the 'docker' directory.
      - name: Build Docker Image
        working-directory: ./docker  # Specify the Docker configuration directory
        run: |
          docker build -t webapp:latest .  # Build the Docker image and tag it as 'webapp:latest'
